### PR TITLE
Cleaning

### PR DESCRIPTION
**Pull request by MIraola**
Implement many different modifications to clean the code. Main modifications:

- Clean routines for old tables that were removed from the code.
- Remove other unused routines.
- Move `short()` from `cli.py` to `aux.py`.
- Make some error messages more explicit.
- Move `__shortIG()` from `kpoint.py` to `gvector.py` as `shortIG()`.

### CODE REVIEW

**Comment by MIraola** [comment]
Do you know why it includes commits that already are in `stepan-tsirkin:master`? Maybe because they were included in a squeezed form? The first commit of the current modification is `192ad1e`.

**Comment by stepan-tsirkin** [comment]
> Do you know why it includes commits that already are in stepan-tsirkin:master? Maybe because they were included in a squeezed form? The first commit of the current modification is 192ad1e.

Yes, probably it is a case.  You need to resolve conflicts now.

**Comment by MIraola** [comment]
I have resolved the conflicts. Now, should we merge it or rebase it? Do you think that rebasing may avoid repeating commits preceding ` 192ad1e`?

**Comment by stepan-tsirkin** [comment]
I am not sure how it exactly works, but I think if you "squash and merge", the PR will appear in history as a single commit containing the diff of the branches. So, try that and see.

**Pull request merged**
