### PR TITLE
implemented spin-polarized calcualtions for quantum espresso

### PR DESCRIPTION
**Pull request by stepan-tsirkin**
Hi, I implemented reading of spin-polarized bandstructure, for quantum-espresso only, so far.   For the other cases (scalar non-polarized and spinor wavefunctions) it works as previously.

What do you think, should I merge this PR before that of @mkhorton  , or after that? Which way will cause less problems?

### CODE REVIEW

**Comment by mkhorton** [comment]
I think both ways will create merge conflicts in `bandstructure.py`.

If you merge #10 first, and then merge changes back to this branch, you will have the benefit of the tests being run. It's not a problem to resolve the merge conflicts however if you want to merge #13 first.

**Comment by stepan-tsirkin** [comment]
Ok, let's merge #10 first

**Comment by stepan-tsirkin** [comment]
@mkhorton  , I see that the tests fail because  I added an import from .bandstructure.py in the __init__.py
I understand, that it is because the virtual environment is 'bare' - it has no other packages installed.  The same happened on my local machine, when I started testing on the venv, it first gave me those import errors, and after installing numpy,scipy and lazy_property - it worked. 
I guess, if I remove this import - it will work.  but is there a way to fix this, so that importing in __init__.py is allowed, and the tests install dependencies before importing irrep?

**Comment by mkhorton** [comment]
It's unclear why they're failing -- the line [here](https://github.com/stepan-tsirkin/irrep/blob/bb1ec4f63c2b997616b6ab09481f67428917cbed/.github/workflows/tests.yml#L26) should mean that all requirements are installed by the `python setup.py`.

One method is to add a `requirements.txt` in the root level of the project and add an additional line above, `pip install -r requirements.txt` to install all necessary dependencies like numpy etc.

**Comment by stepan-tsirkin** [comment]
@mkhorton  ,  Ithink it happens because already setup.py imports irrep, right?   but the problem does not happen when installing from pip, right? because the .whl already knows about dependancies, or why?

is it a best solution to duplicate requrements in a .tx and in setup.py? or should we read  that .txt from setup.py ?

**Comment by mkhorton** [comment]
> is it a best solution to duplicate requrements in a .tx and in setup.py? or should we read that .txt from setup.py ?

Yes, the usual way people do this is to:

* use `requirements.txt` to have the _specific_ versions of dependencies that are known to work, e.g.

```
numpy==1.20.1
scipy==1.6.1
spglib==1.16.1
lazy_property==0.0.1
click==7.1.2
irreptables==1.0.0
```

* use `setup.py` to set the version ranges that are expected to be compatible, e.g. as it currently is is fine: `["numpy", "scipy>=1.0", "spglib>=1.14", "lazy_property", "Click", "irreptables"]`

**Pull request merged**
