### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by MIraola**
This PR improves the automatic tests:

- Create a separate file for the test of each system to avoid having a long file with all tests in it. Improves **readability** of `pytest` output and testing scripts.
- **Implement comparisons for more quantities**, like space group number, energy levels, number of inversion-odd pairs, traces of symmetries,... Previously only some of the irreps and their characters where compared.
- Implement comparisons of arrays, integers, floats, booleans,... instead of comparisons between strings (previously only strings were compared). This way the **comparisons are more robust**.
- Create reference output file `ref_output.json` from which the reference quatitites to be compared will be parsed.
- Correct the file `test.yml` that governs the automatic tests run in Github. There was a problem when installing packages with `python3.9`.

### CODE REVIEW

**Comment by MIraola** [comment]
I forgot to mention that the tests run successfully with `pytest` in the CLI. In Github they fail due to a problem when installing some packages. I will check why.

**Comment by MIraola** [comment]
Fixed the issue with automatic tests in Github. The problem was in the step of installing the package with `python3.9`. Substituting the line `python setup.py develop` by `pip install -e .` fixed it.

**Review by stepan-tsirkin — APPROVED** [review]
Looks good. Thanks for the extensive work.

**Comment by MIraola** [comment]
Thanks!

**Pull request merged**
