### PR TITLE
 a bit modified setup.py

### PR DESCRIPTION
**Pull request by stepan-tsirkin**
another try to pass tests

### CODE REVIEW

**Comment by stepan-tsirkin** [comment]
Matthew @mkhorton , do you have an idea why the wannier_spin test is failing now?  The tests were passing with the previous PR, and I changed only requirements.

**Comment by stepan-tsirkin** [comment]
It is even more weird, I am trying to run tests on older commits locally, and they all fail in the same place. But with the prevvious PR tests passed. What's going on?

**Comment by mkhorton** [comment]
The error is in the logs:

```
File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/irrep/__gvectors.py", line 61, in calc_gvectors
E             etot=norm((K+np.array(igp)).dot(B))**2/twomhbar2
E         ValueError: operands could not be broadcast together with shapes (4,) (3,) 
```

This error causes `irrep` to exit with exit code 1 (i.e. a crash, rather than exit code 0 which we want).

**Comment by stepan-tsirkin** [comment]
I see, maybe I can debug it, but how could it pass the test a few commits ago, if I did not change the code, only the installation of dependancies? Isn't it weird?

**Comment by mkhorton** [comment]
I just want to reference the previous comment in this thread too, maybe it will help: https://github.com/stepan-tsirkin/irrep/pull/13#issuecomment-782516201

**Pull request closed without merging**
